stages:
  train:
    cmd: python model/src/train.py 2>&1 | tee train.log
    deps:
        - datasets/samples/preprocessed/
        - model/src/train.py
        - datasets/trainlist.txt
        - params.yaml
    outs:
        - model/train/${model_name}/checkpoint.h5:
            checkpoint: true
        - model/train/${model_name}/best.h5:
            checkpoint: true
    metrics:
        - model/train/${model_name}/best.json:
            checkpoint: true
        - model/train/${model_name}/checkpoint.json:
            checkpoint: true
    plots:
        - model/train/${model_name}/plot.csv:
            cache: false
  evaluate:
    cmd: python model/src/evaluator.py model/train/${model_name}/best.h5 params.yaml datasets/testlist.txt  --output model/eval/${model_name}/ 2>&1 | tee eval.log
    deps:
        - model/train/${model_name}/best.h5
        - model/src/evaluator.py
        - datasets/testlist.txt
        - params.yaml
    metrics:
        - model/eval/${model_name}/metrics.json:
            cache: false
        - model/eval/${model_name}/errors.csv:
            cache: false

