stages:
  decompress_dataset:
    cmd: sh datasets/scripts/decompress_dataset.sh
    deps:
    - datasets/preprocessed.tar.xz
    outs:
    - datasets/samples/preprocessed
  train:
    cmd: python model/src/train.py
    deps:
    - datasets/samples/preprocessed/
    - model/src/train.py
    - params.yaml
    outs:
    - model/train/checkpoint.h5:
        checkpoint: true
    - model/train/checkpoint.json:
        checkpoint: true
    - model/train/best.h5:
        checkpoint: true
    - model/train/best.json:
        checkpoint: true
