# model name
model_name: WaveNet

# batch size used during fit
batch_size: 64

# number of epochs to train the model
epochs: 120

# number of simultaneous files to open
file_batch_size: 5

# save model at every n-th epoch (<=0 to disable)
keep_checkpoint_at_every_n_epoch: 10

# amount of overlap between consecutive windows
window_overlap: 0.5

Cnn:
  input_size: 32

SmallCnn:
  input_size: 32

WaveNet:
  lr: 0.0001

TimeDistributedCnnLstm: {}

# data augmentation operations
DataAugmentation:
  enabled: true
  
  # define which operations should be applied
  operations:

    # apply white noise
    white_noise:
      prob: 0.2 # probability to be applied
      sigma_min: 0.05 # minimum value of noise signal
      sigma_max: 0.9 # maximum value of noise signal

    multiplier:
      prob: 0.2 # probability to be applied
      min: 0.5 # minimum value
      max: 1.5 # maximum value

  order: [multiplier, white_noise]
